= Documentacion

== Introduccion
Este repositorio contine los recursos para desplegar un Custom Resource Definintion y sus correspondientes Custom Resources.

El objetivo es demostrar el uso de la API extensible de Kubernetes

== 1. Instalar `kubectl`, KIND y levantar un cluster nuevo
`kubectl` es la aplicación en línea de comandos para utilizar un cluster de Kubernetes. Aquí tenéis las instrucciones de instalación https://kubernetes.io/docs/tasks/tools/

KIND es Kubernetes In Docker y aquí tenéis la guia de instalación https://kind.sigs.k8s.io/docs/user/quick-start/#installation

Para levantar un cluster
[source,shell]
----
kind create cluster --name kubernetes-software-development
----

Prueba que fue bien
[source,shell]
----
kubecolor get pods
---
Y el resultado deberá ser `No resources found in default namespace`

== 2. Desplegar CRD
[source,shell]
----
kubectl apply -f crd-ciudades.yaml
----

== 3. Desplegar un Custom Resources
[source,shell]
----
kubectl apply -f custom-resources/cr-oviedo.yaml
# Check the custom resource was deployed
kubectl get ciudades
# Describe the custom resource with the output in JSON
kubectl get ciudades oviedo.asturias -o json
# Remove the custom resource
kubectl delete ciudades oviedo.asturias
----

== Desplegar todos los Custom Resources en el directorio
[source,shell]
----
kubectl apply -f custom-resources/aviles.yaml
kubectl apply -f custom-resources/gijon.yaml
kubectl apply -f custom-resources/oviedo.yaml
kubectl apply -f custom-resources/santibanes-de-murias.yaml
kubectl get ciudades
----
